### PR TITLE
Managed environment import fails

### LINKED ISSUE #1122: Managed environment import fails
## Describe the bug

Importing managed environment fails with following error:

```
Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-power-platform_v4.1.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x7ff622b344bf]

goroutine 101 [running]:
[github.com/microsoft/terraform-provider-power-platform/internal/services/environment.(*Client).GetEnvironment(0xc000092668](http://github.com/microsoft/terraform-provider-power-platform/internal/services/environment.(*Client).GetEnvironment(0xc000092668), {0x7ff6230d4410, 0xc0000544d0}, {0x0, 0x0})
        [github.com/microsoft/terraform-provider-power-platform/internal/services/environment/api_environment.go:266](http://github.com/microsoft/terraform-provider-power-platform/internal/services/environment/api_environment.go:266) +0x4df
[github.com/microsoft/terraform-provider-power-platform/internal/services/managed_environment.(*ManagedEnvironmentResource).Read(0xc000092640](http://github.com/microsoft/terraform-provider-power-platform/internal/services/managed_environment.(*ManagedEnvironmentResource).Read(0xc000092640), {0x7ff6230d4368?, 0xc00083bf50?}, {{{{0x7ff6230da330, 0xc000043170}, {0x7ff622dc4b60, 0xc0000430b0}}, {0x7ff6230e2b98, 0xc00039cc80}}, 0x0, ...}, ...)
        [github.com/microsoft/terraform-provider-power-platform/internal/services/managed_environment/resource_managed_environment.go:230](http://github.com/microsoft/terraform-provider-power-platform/internal/services/managed_environment/resource_managed_environment.go:230) +0x1fe
[github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc00024a308](http://github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc00024a308), {0x7ff6230d4368, 0xc00083bf50}, 0xc000412eb0, 0xc0000b55d8)
        [github.com/hashicorp/terraform-plugin-framework@v1.17.0/internal/fwserver/server_readresource.go:156](http://github.com/hashicorp/terraform-plugin-framework@v1.17.0/internal/fwserver/server_readresource.go:156) +0xb8e
[github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc00024a308](http://github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc00024a308), {0x7ff6230d4368?, 0xc00083be60?}, 0xc0004126e0)
        [github.com/hashicorp/terraform-plugin-framework@v1.17.0/internal/proto6server/server_readresource.go:71](http://github.com/hashicorp/terraform-plugin-framework@v1.17.0/internal/proto6server/server_readresource.go:71) +0x592
[github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000246aa0](http://github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc000246aa0), {0x7ff6230d4368?, 0xc00083b3b0?}, 0xc000054460)
        [github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov6/tf6server/server.go:863](http://github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov6/tf6server/server.go:863) +0x2f3
[github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x7ff622efb600](http://github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler(%7B0x7ff622efb600), 0xc000246aa0}, {0x7ff6230d4368, 0xc00083b3b0}, 0xc000360600, 0x0)
        [github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:753](http://github.com/hashicorp/terraform-plugin-go@v0.29.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:753) +0x1a9
[google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e2400](http://google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e2400), {0x7ff6230d4368, 0xc00083b320}, 0xc0001522a0, 0xc000332240, 0x7ff623832138, 0x0)
        [google.golang.org/grpc@v1.75.1/server.go:1431](http://google.golang.org/grpc@v1.75.1/server.go:1431) +0xfe8
[google.golang.org/grpc.(*Server).handleStream(0xc0001e2400](http://google.golang.org/grpc.(*Server).handleStream(0xc0001e2400), {0x7ff6230d4d48, 0xc0003fc000}, 0xc0001522a0)
        [google.golang.org/grpc@v1.75.1/server.go:1842](http://google.golang.org/grpc@v1.75.1/server.go:1842) +0xb95
[google.golang.org/grpc.(*Server).serveStreams.func2.1()](http://google.golang.org/grpc.(*Server).serveStreams.func2.1())
        [google.golang.org/grpc@v1.75.1/server.go:1061](http://google.golang.org/grpc@v1.75.1/server.go:1061) +0x7f
created by [google.golang.org/grpc.(*Server).serveStreams.func2](http://google.golang.org/grpc.(*Server).serveStreams.func2) in goroutine 52
        [google.golang.org/grpc@v1.75.1/server.go:1072](http://google.golang.org/grpc@v1.75.1/server.go:1072) +0x11d

Error: The terraform-provider-power-platform_v4.1.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Sample Terraform Code

```hcl
+ resource "powerplatform_managed_environment" "managed_development" {
      + copilot_allow_grant_editor_permissions_when_shared = true
      + copilot_limit_sharing_mode                         = "NoLimit"
      + copilot_max_limit_user_sharing                     = -1
      + environment_id                                     = "00000000-0000-0000-0000-000000000000"
      + id                                                 = (known after apply)
      + is_group_sharing_disabled                          = true
      + is_usage_insights_disabled                         = true
      + limit_sharing_mode                                 = "ExcludeSharingToSecurityGroups"
      + max_limit_user_sharing                             = 10
      + power_automate_is_sharing_disabled                 = false
      + protection_level                                   = (known after apply)
      + solution_checker_mode                              = "None"
      + suppress_validation_emails                         = true
    }

```

**REMINDER: REMOVE SENSITIVE DATA SUCH AS SECRETS, USER NAMES, EMAILS, TENANT INFORMATION, ETC.**

### Expected behavior

Resource should be imported successfully

## System Information

- Provider Version: 4.1.0
- OS & Version: Windows 11

## Additional context

-

### PR DESCRIPTION
**Pull request by mawasile**
This pull request enhances error handling and validation for the managed environment resource, ensuring that environments meet prerequisites before being managed. It introduces explicit error returns when required features are missing and adds unit tests to verify these scenarios.

**Error handling and validation improvements:**

* The `populateStateFromEnvironment` method in `resource_managed_environment.go` now returns errors if Dataverse is not enabled or if the managed environment feature is missing, rather than silently proceeding. This ensures that only valid environments can be managed and provides clear error messages. [[1]](diffhunk://#diff-937dad36a5e0576348afcebbf45d3463e180227779b6360e89ddbe6d6e606a34L436-R460) [[2]](diffhunk://#diff-937dad36a5e0576348afcebbf45d3463e180227779b6360e89ddbe6d6e606a34L499-R523)
* The `Create`, `Read`, and `Update` methods now handle errors returned from `populateStateFromEnvironment`, adding diagnostic errors and preventing further processing if prerequisites are not met. [[1]](diffhunk://#diff-937dad36a5e0576348afcebbf45d3463e180227779b6360e89ddbe6d6e606a34L211-R215) [[2]](diffhunk://#diff-937dad36a5e0576348afcebbf45d3463e180227779b6360e89ddbe6d6e606a34L248-R259) [[3]](diffhunk://#diff-937dad36a5e0576348afcebbf45d3463e180227779b6360e89ddbe6d6e606a34L304-R318)

**Testing enhancements:**

* Added two new unit tests in `resource_managed_environment_test.go`:
  - One test verifies that an error is returned when attempting to create a managed environment without Dataverse enabled.
  - Another test checks for an error when the managed environment feature is not enabled.
* New test data files were added to simulate these scenarios: `Validate_Create_No_Dataverse/get_environment.json` and `Validate_Create_No_Managed_Env/get_environment.json`. [[1]](diffhunk://#diff-2468bdb633e70fe3f0c25229fd4531c9521b56039a26077ea035bfcc91e5500bR1-R22) [[2]](diffhunk://#diff-19632673c3e974b24ad4201e94af6857adad9f1eb2ffc788e6ab609e8d2e002dR1-R33)

**Build process:**

* Minor update to the `Makefile` to change the order of tasks in the `precommit` target, placing `userdocs` before `unittest`.

### CODE REVIEW

File: internal/helpers/contexts_test.go [hunk 1]
```diff
@@ -19,24 +18,6 @@ func TestUnitCheckContextTimeout_NoTimeout(t *testing.T) {
 	}
 }
 
-func TestUnitCheckContextTimeout_WithTimeout(t *testing.T) {
```
Comment (ianjensenisme) [inline internal/helpers/contexts_test.go:22]: What does this haver to do with the issue being resolved in this PR?

**Review by ianjensenisme — COMMENTED** [review]
One open Q on a change that you might want to separate into its own PR

File: internal/helpers/contexts_test.go (hunk 1 above)
Comment (mawasile) [reply internal/helpers/contexts_test.go:22]: nothing, but this is a test that keeps failing randomly on nightly builds, I've removed it as a part of this PR a while ago when I was working on that

File: internal/services/managed_environment/resource_managed_environment.go [hunk 2]
```diff
@@ -196,7 +196,20 @@ func (r *ManagedEnvironmentResource) Create(ctx context.Context, req resource.Cr
...
-	err := r.ManagedEnvironmentClient.EnableManagedEnvironment(ctx, managedEnvironmentDto, plan.EnvironmentId.ValueString())
+	envPreCheck, err := r.ManagedEnvironmentClient.environmentClient.GetEnvironment(ctx, plan.EnvironmentId.ValueString())
+	if err != nil {
+		resp.Diagnostics.AddError(fmt.Sprintf("Client error when reading environment %s", r.FullTypeName()), err.Error())
+		return
+	}
+	if envPreCheck.Properties.LinkedEnvironmentMetadata == nil {
+		resp.Diagnostics.AddError(
+			fmt.Sprintf("Error enabling managed environment for %s", r.FullTypeName()),
+			fmt.Sprintf("environment '%s' requires Dataverse to be enabled before it can be managed", envPreCheck.Name),
```
Comment (polatengin) [inline internal/services/managed_environment/resource_managed_environment.go:207]: env.Name is GUID, if we want to display the name of the environment we should use env.Properties.DisplayName.

do you want to display the GUID, or did you mean to display the environment name?

File: internal/services/managed_environment/resource_managed_environment.go [hunk 3]
```diff
@@ -434,83 +449,84 @@ func (r *ManagedEnvironmentResource) buildManagedEnvironmentDto(plan *ManagedEnv
 }
 
 func (r *ManagedEnvironmentResource) populateStateFromEnvironment(ctx context.Context, plan *ManagedEnvironmentResourceModel, env *environment.EnvironmentDto, diagnostics *diag.Diagnostics) {
+	if env.Properties.LinkedEnvironmentMetadata == nil {
+		diagnostics.AddError(
+			fmt.Sprintf("Error populating state from environment for %s", r.FullTypeName()),
+			fmt.Sprintf("environment '%s' requires Dataverse to be enabled before it can be managed", env.Name),
```
Comment (polatengin) [inline internal/services/managed_environment/resource_managed_environment.go:455]: env.Name is GUID, if we want to display the name of the environment we should use env.Properties.DisplayName.

do you want to display the GUID, or did you mean to display the environment name?

File: internal/services/managed_environment/resource_managed_environment.go [hunk 4]
```diff
@@ -434,83 +449,84 @@ func (r *ManagedEnvironmentResource) buildManagedEnvironmentDto(plan *ManagedEnv
 }
 
 func (r *ManagedEnvironmentResource) populateStateFromEnvironment(ctx context.Context, plan *ManagedEnvironmentResourceModel, env *environment.EnvironmentDto, diagnostics *diag.Diagnostics) {
+	if env.Properties.LinkedEnvironmentMetadata == nil {
```
Comment (polatengin) [inline internal/services/managed_environment/resource_managed_environment.go:452]: _please resolve this comment if I'm wrong_

if managed environment setting is disabled outside of terraform for the environment, Read will start failing. Which will force the user to run `terraform state rm` to recover.

I think for Create and Update this experience is ok, but for `Read` operations should we consider calling `State.RemoveResource(ctx)` instead?

**Review by polatengin — APPROVED** [review]
lgtm, I left a few comments
