### PR TITLE
Fix: Preserve security group updates for environments

### LINKED ISSUE #1130: Updating `powerplatform_environment` does not persist `dataverse.security_group_id` for non-Developer environments
## Describe the bug

Updating a non-Developer `powerplatform_environment` with a changed `dataverse.security_group_id` does not persist the new value. Terraform plans the change, but the provider sends an update payload that drops the security group ID, so the old value remains in place and apply fails with an inconsistent result.

### Sample Terraform Code

```hcl
resource "powerplatform_environment" "example" {
  display_name     = "example"
  location         = "europe"
  environment_type = "Sandbox"

  dataverse = {
    language_code     = "1033"
    currency_code     = "USD"
    security_group_id = "11111111-1111-1111-1111-111111111111"
  }
}
```

### Expected behavior

When `dataverse.security_group_id` is changed for a non-Developer environment, the provider should submit the new value and Terraform should complete successfully without drift or inconsistent state errors.

## System Information

- Provider Version: current `main` / unreleased build
- OS & Version: MacOS

## Additional context

This appears to affect the update path for existing Dataverse-backed environments. The plan contains the new `security_group_id`, but the update request does not preserve it for non-Developer environments.

### PR DESCRIPTION
**Pull request by AdamCoulterOz**
## Summary
- preserve the planned `dataverse.security_group_id` when updating existing non-Developer environments
- stop dropping the security group ID from the linked environment metadata update payload

## Testing
- go test ./internal/services/environment/...

Closes #1130

### CODE REVIEW

File: internal/services/environment/resource_environment.go [hunk 1]
```diff
@@ -703,7 +703,7 @@ func updateExistingDataverse(ctx context.Context, plan *SourceModel, environment
 	}
 
 	if plan.EnvironmentType.ValueString() != EnvironmentTypesDeveloper {
-		environmentDto.Properties.LinkedEnvironmentMetadata.SecurityGroupId = types.StringNull().ValueString()
+		environmentDto.Properties.LinkedEnvironmentMetadata.SecurityGroupId = dataverseSourcePlanModel.SecurityGroupId.ValueString()
```
Comment (mawasile) [inline internal/services/environment/resource_environment.go]: thanks for spotting, this is clearly a bug. Dev environment do not have security groups. 
The IF statement from 705 can be removed, we don't have to check type of an env here anymore

**Review by mawasile — CHANGES_REQUESTED** [review]
- you should run `make precommit` before creating PR that will run linter, unit tests and refresh docs.
- we use changelog to track release changes. If you are using AI you can just ask it to create new changelog and pick a correct change type.

**Comment by AdamCoulterOz** [comment]
> * you should run `make precommit` before creating PR that will run linter, unit tests and refresh docs.
> * we use changelog to track release changes. If you are using AI you can just ask it to create new changelog and pick a correct change type.

@mawasile `make precommit` fails repo-wide on unrelated pre-existing revive findings outside this PR

File: internal/services/environment/resource_environment.go (hunk 1 above)
Comment (AdamCoulterOz) [reply internal/services/environment/resource_environment.go]: Addressed. I removed the environment type check and now always assign `SecurityGroupId` from the plan. For Developer environments the value is empty, so it is omitted from the DTO payload.

**Review by mawasile — DISMISSED** [review]

**Review by mawasile — APPROVED** [review]
